<?php

use Drupal\Core\Block\BlockPluginInterface;
use Drupal\node\NodeInterface;

/**
 * @file
 * Hooks and theme helpers for the Node Block module.
 */

/**
 * Implements hook_theme_suggestions_block_alter().
 */
function node_block_theme_suggestions_block_alter(array &$suggestions, array $vars): void {
  // Support for node block theme suggestions.
  if (isset($vars['elements']['#configuration']['theme_suggestion'])) {
    $base_plugin_id = str_replace('-', '_', $vars['elements']['#base_plugin_id']);
    $theme_suggestion = $vars['elements']['#configuration']['theme_suggestion'];

    if (!empty($theme_suggestion)) {
      $theme_suggestion = preg_replace('@[^a-z0-9]+@', '_', strtolower($theme_suggestion));
      $suggestions[] = 'block__' . $base_plugin_id . '__' . $theme_suggestion;
    }
  }
}

/**
 * Implements hook_preprocess_block().
 */
function node_block_preprocess_block(array &$variables): void {
  $node = \Drupal::routeMatch()->getParameter('node');

  if ($node instanceof NodeInterface) {
    $variables['node'] = $node;
  }
}

/**
 * Implements hook_block_build_BASE_BLOCK_ID_alter().
 */
function node_block_block_build_node_block_alter(array &$build, BlockPluginInterface $block): void {
  // Skip BigPipe for this block.
  $build['#create_placeholder'] = FALSE;
}